type Query {
    games: [GameDto!]!,
    game(id: ID!): GameDto,
    gameRatings(gameId: ID!): [RatingDto!]!,
    gameRating(gameId: ID!, id: ID!): RatingDto
}

type Mutation {
    updateRating(input: RatingInput!): Boolean,
    updateFactor(input: FactorInput!): Boolean,
    updateAdjustment(input: AdjustmentInput!): Boolean,
    createGame(input: CreateGameInput!): GameDto,
    updateGame(input: GameInput!): Boolean
}


enum AdjustmentType {
    READ_ONLY,
    IMPACTFUL
}


type GameDto {
    id: ID!,
    name: String!,
    description: String!,
    factorScale: Scale
}


type RatingDto {
    id: ID!,
    name: String!,
    description: String!,
    factors: [FactorDto]!,
    adjustments: [AdjustmentDto]!,
    value: Float,
}

type Scale {
    min: Float,
    max: Float
}


type FactorDto {
    id: ID,
    name: String,
    description: String,
    value: Float
}


type AdjustmentDto {
    id: ID,
    type: AdjustmentType,
    value: Float,
    valueScale: Scale
}

input GameInput {
    id: ID!,
    name: String,
    description: String
}

input CreateGameInput {
    name: String!,
    description: String!
}

input RatingInput {
    gameId: ID!,
    ratingId: ID!,
    value: Float
}

input FactorInput {
    gameId: ID!,
    ratingId: ID!,
    factorId: ID!,
    value: Float
}

input AdjustmentInput {
    gameId: ID!,
    ratingId: ID!,
    adjustmentId: ID!,
    value: Float
}
